version: "3"

services:
  backend:
    image: picasso-backend
    container_name: picasso-backend
    build: ./picasso-backend
    environment:
      - IMG_SRC_URL=https://pastebin.com/raw/BmA8B0tY
    ports:
      - "8000:8000"
  frontend:
    depends_on: 
      - "backend"
    image: picasso-frontend
    container_name: picasso-frontend
    build: ./picasso-frontend
    ports:
      - "8080:5000"